stages:
  - test

test:
  stage: test
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-21-98-254.us-east-2.compute.amazonaws.com "cd ~; docker-compose up -d;"
