image : openjdk:11-jdk

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DEPLOYMENT: cart
  IMAGE: cart
stages:
  - build
  - docker-build-push
  - deploy
maven-build:
  image : maven:3.6-jdk-11
  stage : build
  script:
    - 'mvn clean install -s ci_settings.xml'
  artifacts:
    paths:
      - target/*.jar
docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: docker-build-push
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_HUB_USER" -p $DOCKER_ACCESS_TOKEN
  script:
    - docker build -t sharmasahil95/amcart-cart-service:$CI_COMMIT_SHORT_SHA .
    - docker push sharmasahil95/amcart-cart-service:$CI_COMMIT_SHORT_SHA
  only:
    - master
deploy-image:
  stage: deploy
  image: dwdraju/gke-kubectl-docker
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $GCP_PROJECT_ID
    - kubectl set image deployment/$DEPLOYMENT $IMAGE=sharmasahil95/amcart-cart-service:$CI_COMMIT_SHORT_SHA
  only:
    - master
