image: docker:latest

services:
  - docker:dind

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
stages:
  - build
  - deploy

build:
  stage: build
  image: node:12.20-alpine
  script:
    - echo $AWS_ACCESS_KEY_ID $AWS_REGION $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY $CDN_DISTRIBUTION_ID
    - npm install --silent
    - npm run build --  --prod
  artifacts:
    paths:
    - build/
    expire_in: 1 day
  only:
    - master
deploy:
  stage: deploy
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    # - eval $(aws ecr get-login --no-include-email --region ap-south-1 | sed 's|https://||')
    - aws configure list
  script:
    - aws s3 cp build/ s3://amcart/ --recursive --include "*"
    - aws cloudfront create-invalidation --distribution-id E2EC7VBAM4FLDI --paths "/*"
  only:
    - master

