/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_2HNi6avv8",
    "aws_user_pools_web_client_id": "5pg97dn9fcec5bbvp3aii8stjo",
    "oauth": {
        "domain": "amcart.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://d3w293tnjvlysy.cloudfront.net/home",
        "redirectSignOut": "https://d3w293tnjvlysy.cloudfront.net/home",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};

export default awsmobile;
